### ISSUE TITLE
Flyspell-babel warning: no dictionary installed for foreignlanguage

### ISSUE THREAD

**Issue by Geremia** [phimuemue/emacs-hacks#3]
I can't get Flyspell-babel to change dictionaries when my cursor is placed in a different environment.

For details on my setup, see this TeX StackExchange post: "[Flyspell-babel warning: no dictionary installed for foreignlanguage](https://tex.stackexchange.com/q/325453/36603)"

cf. [`flyspell-babel.el`](https://github.com/phimuemue/emacs-hacks/blob/master/flyspell-babel.el#L401) line 401.

**Comment by Geremia** [comment]
The issue was that I had

```
@(setq flyspell-babel-verbose t)

(setq flyspell-babel-to-ispell-alist
       '(("german" "german")
         ("italian" "italian")
         ("latin" "latin")))

(setq flyspell-babel-command-alist
      '(("fgi" "german")
        ("fii" "italian")
        ("fl" "latin")
    ("fli" "latin")))
```

in `~/.emacs`, not `flyspell-babel.el`!

Thus, this issue is resolved.

**Comment by phimuemue** [comment]
If you don't have any objections, I'll close this issue. Ok?

**Comment by Geremia** [comment]
@phimuemue yes, you may close it.
